spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: Your-client-id
            client-secret: Your-secret-key
            scope:
              - openid
              - profile
              - email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
    jwt:
      secret: YOUR_SECRET_KEY_MUST_BE_AT_LEAST_32_CHARACTERS_LONG

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
